"""Build the MetaMath prompt pool for C_math, one file per augmentation view.

MetaMathQA augments GSM8K-train and MATH-train questions four ways (AnsAug,
Rephrased, SV, FOBAR) and keeps `original_question` plus `type`, so the pool can
be reconstructed deterministically from those two fields.

Design of the default pool:

  canonical   every unique original_question, verbatim -- 100% coverage of the
              underlying problems, and the phrasing style the math evals use
  augmented   exactly ONE augmented view per question, so every problem carries
              the same weight (C is a token-mean, so letting an arbitrary subset
              contribute two rows would silently up-weight those problems)

AnsAug is never used: its `query` is the original question verbatim, so as a
"second view" it would just duplicate the canonical row, and its real value
(alternative reference solutions) is irrelevant here because the targets are
regenerated by self-distillation anyway.

Output is one JSONL per view (canonical / rephrased / sv / fobar). Splitting by
view matters because generate_replay_targets.py rewrites each record with a
fixed field set and would drop a `view` column, making per-view diagnostics
impossible afterwards. Self-distill each file separately, then point
collect_cov at the glob.

Two modes:
  default        quota-based, one augmented view per question (the real pool)
  --all_views 1  every available view for each selected question, for a PAIRED
                 pilot where the same problems appear under all views
"""

from __future__ import annotations

import argparse
import json
import os
import random
from collections import defaultdict
from pathlib import Path
from typing import Any

# Native MetaMathQA query-augmentation proportions, excluding AnsAug:
#   GSM  80K Rephrased + 40K SV + 40K FOBAR
#   MATH 50K Rephrased + 15K SV + 15K FOBAR
NATIVE_WEIGHTS = {
    "GSM": {"Rephrased": 0.5, "SV": 0.25, "FOBAR": 0.25},
    "MATH": {"Rephrased": 0.625, "SV": 0.1875, "FOBAR": 0.1875},
}

AUG_VIEWS = ("Rephrased", "SV", "FOBAR")

REQUIRED_COLUMNS = ("type", "query", "original_question", "response")

# Suffix -> datasets loader name, in the order preferred when a directory holds
# several formats. ".json" covers MetaMathQA's official single-array release.
DATA_SUFFIXES = ((".parquet", "parquet"), (".jsonl", "json"), (".json", "json"))

# Files a save_to_disk / hub snapshot leaves behind that are not data.
METADATA_NAMES = frozenset(
    {"dataset_info.json", "state.json", "dataset_dict.json", "config.json"}
)


def parse_args() -> argparse.Namespace:
    """Parse the MetaMathQA location, quotas, and output settings."""

    parser = argparse.ArgumentParser(description="Build the MetaMath C_math prompt pool.")
    parser.add_argument(
        "--metamath_path",
        type=str,
        default="",
        help="Local jsonl/parquet/save_to_disk dir. Empty falls back to --metamath_repo.",
    )
    parser.add_argument("--metamath_repo", type=str, default="meta-math/MetaMathQA")
    parser.add_argument("--split", type=str, default="train")
    parser.add_argument("--out_dir", type=str, required=True)
    parser.add_argument("--prefix", type=str, default="metamath_cmath")
    parser.add_argument("--sources", type=str, default="GSM,MATH")
    parser.add_argument(
        "--aug_weights",
        type=str,
        default="",
        help="Override native mix, e.g. 'Rephrased=1.0' or 'Rephrased=0.8,SV=0.1,FOBAR=0.1'.",
    )
    parser.add_argument(
        "--max_questions_per_source",
        type=int,
        default=0,
        help="Cap unique questions per source; 0 = all. Use a small value for the pilot.",
    )
    parser.add_argument(
        "--all_views",
        type=int,
        default=0,
        help="1 emits every available view per question (paired pilot) instead of quotas.",
    )
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument(
        "--tokenizer_path",
        type=str,
        default=(
            str(Path(os.environ["MODEL_DIR"]) / os.environ.get("MODEL_NAME", "Qwen3-1.7B"))
            if os.environ.get("MODEL_DIR")
            else ""
        ),
        help="Model dir for prompt-token shares; defaults to $MODEL_DIR/$MODEL_NAME when set.",
    )
    return parser.parse_args()


def find_data_files(directory: Path) -> tuple[str, list[str]]:
    """Locate the data files inside a plain directory of downloaded files."""

    for suffix, fmt in DATA_SUFFIXES:
        matches = sorted(
            path
            for path in directory.rglob(f"*{suffix}")
            if path.is_file() and path.name not in METADATA_NAMES
        )
        if matches:
            return fmt, [str(path) for path in matches]
    raise ValueError(
        f"No .parquet/.jsonl/.json data files found under {directory}. "
        "Point --metamath_path at the file itself or a directory containing it."
    )


def load_local(fmt: str, files: list[str]):
    """Read local data files without any Hub round-trip.

    load_dataset("json", ...) first resolves the packaged builder remotely, which
    hangs on an offline or firewalled node. Dataset.from_json / from_parquet
    instantiate that builder directly, so they stay local while keeping the
    Arrow backing (important at 395K rows).
    """

    from datasets import Dataset

    if fmt == "parquet":
        return Dataset.from_parquet(files if len(files) > 1 else files[0])
    return Dataset.from_json(files if len(files) > 1 else files[0])


def load_metamath(args: argparse.Namespace):
    """Load MetaMathQA from a save_to_disk dir, a plain dir, a file, or the hub."""

    from datasets import load_dataset, load_from_disk

    if not args.metamath_path:
        return load_dataset(args.metamath_repo, split=args.split)

    source = Path(args.metamath_path)
    if source.is_dir():
        if (source / "dataset_info.json").exists() or (source / "dataset_dict.json").exists():
            dataset = load_from_disk(str(source))
            if hasattr(dataset, "keys"):
                dataset = dataset[args.split if args.split in dataset else next(iter(dataset))]
            return dataset
        fmt, files = find_data_files(source)
        print(f"loading {len(files)} {fmt} file(s) from {source}")
        return load_local(fmt, files)

    fmt = dict(DATA_SUFFIXES).get(source.suffix.lower())
    if fmt is None:
        raise ValueError(f"Unsupported MetaMath file type: {source}")
    return load_local(fmt, [str(source)])


def split_type(type_value: str) -> tuple[str, str]:
    """Turn a MetaMathQA `type` into (source, augmentation)."""

    text = str(type_value)
    source = "GSM" if text.startswith("GSM") else "MATH" if text.startswith("MATH") else ""
    aug = text.split("_", 1)[1] if "_" in text else ""
    return source, aug


def index_questions(dataset, sources: list[str]) -> dict[str, dict[str, dict[str, list[int]]]]:
    """Map source -> original_question -> augmentation -> row indices.

    Only the two small columns are materialized; `query` and `response` are
    fetched later for the selected rows only, which keeps peak memory low on a
    395K-row corpus.
    """

    types = dataset["type"]
    questions = dataset["original_question"]
    index: dict[str, dict[str, dict[str, list[int]]]] = {src: defaultdict(dict) for src in sources}
    for row_id, (type_value, question) in enumerate(zip(types, questions)):
        source, aug = split_type(type_value)
        if source not in index or not aug:
            continue
        bucket = index[source].setdefault(question, {})
        bucket.setdefault(aug, []).append(row_id)
    return index


def parse_weights(spec: str) -> dict[str, float] | None:
    """Parse an --aug_weights override into normalized weights."""

    if not spec.strip():
        return None
    weights: dict[str, float] = {}
    for piece in spec.split(","):
        piece = piece.strip()
        if not piece:
            continue
        name, _, value = piece.partition("=")
        name = name.strip()
        if name not in AUG_VIEWS:
            raise ValueError(f"Unknown augmentation {name!r}; expected one of {AUG_VIEWS}")
        weights[name] = float(value)
    total = sum(weights.values())
    if total <= 0:
        raise ValueError("--aug_weights must sum to a positive number")
    return {name: value / total for name, value in weights.items()}


def assign_views(
    questions: list[str],
    available: dict[str, dict[str, list[int]]],
    weights: dict[str, float],
    rng: random.Random,
) -> tuple[dict[str, str], dict[str, int]]:
    """Give each question exactly one augmented view, honoring the quotas.

    Quotas are filled greedily against what each question actually has, so a
    question missing the type its quota would prefer still contributes rather
    than being dropped. Questions with no augmented view at all are skipped and
    counted separately.
    """

    order = list(questions)
    rng.shuffle(order)
    remaining = {view: int(round(weights.get(view, 0.0) * len(order))) for view in AUG_VIEWS}
    # A zero-weight view is excluded outright, never used as a fallback, so
    # --aug_weights "Rephrased=1.0" really means Rephrased only.
    allowed = {view for view in AUG_VIEWS if weights.get(view, 0.0) > 0}

    assignment: dict[str, str] = {}
    stats = {"assigned": 0, "no_aug": 0, "off_quota": 0}
    for question in order:
        options = [
            view
            for view in AUG_VIEWS
            if view in allowed and available[question].get(view)
        ]
        if not options:
            stats["no_aug"] += 1
            continue
        eligible = [view for view in options if remaining[view] > 0]
        if eligible:
            choice = max(eligible, key=lambda view: remaining[view])
        else:
            choice = max(options, key=lambda view: remaining[view])
            stats["off_quota"] += 1
        remaining[choice] -= 1
        assignment[question] = choice
        stats["assigned"] += 1
    return assignment, stats


def canonical_row_id(available: dict[str, list[int]]) -> int:
    """Pick a row to source the (discarded) reference answer for a question."""

    if available.get("AnsAug"):
        return available["AnsAug"][0]
    for aug in AUG_VIEWS:
        if available.get(aug):
            return available[aug][0]
    return next(iter(available.values()))[0]


def build_records(
    dataset,
    index: dict[str, dict[str, dict[str, list[int]]]],
    args: argparse.Namespace,
    rng: random.Random,
) -> tuple[dict[str, list[dict[str, Any]]], dict[str, Any]]:
    """Assemble per-view records and the accompanying manifest counts."""

    views: dict[str, list[dict[str, Any]]] = {"canonical": []}
    for aug in AUG_VIEWS:
        views[aug.lower()] = []
    manifest: dict[str, Any] = {"per_source": {}}

    wanted: dict[int, tuple[str, str, str]] = {}
    for source, per_question in index.items():
        questions = sorted(per_question)
        rng.shuffle(questions)
        if args.max_questions_per_source > 0:
            questions = questions[: args.max_questions_per_source]
        questions.sort()

        source_stats: dict[str, Any] = {"num_questions": len(questions)}
        for question in questions:
            wanted[canonical_row_id(per_question[question])] = (source, "canonical", question)

        if args.all_views:
            counts = {"canonical": len(questions)}
            for question in questions:
                for aug in AUG_VIEWS:
                    rows = per_question[question].get(aug)
                    if rows:
                        wanted[rng.choice(rows)] = (source, aug.lower(), question)
                        counts[aug.lower()] = counts.get(aug.lower(), 0) + 1
            source_stats["counts"] = counts
            source_stats["mode"] = "all_views"
        else:
            weights = parse_weights(args.aug_weights) or NATIVE_WEIGHTS[source]
            assignment, stats = assign_views(
                questions, per_question, weights, rng
            )
            counts = {"canonical": len(questions)}
            for question, aug in assignment.items():
                wanted[rng.choice(per_question[question][aug])] = (source, aug.lower(), question)
                counts[aug.lower()] = counts.get(aug.lower(), 0) + 1
            source_stats["counts"] = counts
            source_stats["weights"] = weights
            source_stats["questions_without_aug"] = stats["no_aug"]
            source_stats["off_quota_assignments"] = stats["off_quota"]
            source_stats["mode"] = "quota"
        manifest["per_source"][source] = source_stats

    row_ids = sorted(wanted)
    selected = dataset.select(row_ids)
    queries = selected["query"]
    responses = selected["response"]
    for row_id, query, response in zip(row_ids, queries, responses):
        source, view, question = wanted[row_id]
        prompt = question if view == "canonical" else query
        views[view].append(
            {
                "inputs": prompt,
                "targets": response,
                "source": source,
                "view": view,
                "original_question": question,
            }
        )
    return views, manifest


def token_shares(views: dict[str, list[dict[str, Any]]], tokenizer_path: str) -> dict[str, Any]:
    """Prompt-token totals per view; C is a token-mean, so shares matter more than counts."""

    from transformers import AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(tokenizer_path)
    totals: dict[str, int] = {}
    for view, records in views.items():
        if not records:
            continue
        encoded = tokenizer([r["inputs"] for r in records], add_special_tokens=False)["input_ids"]
        totals[view] = sum(len(ids) for ids in encoded)
    grand = max(sum(totals.values()), 1)
    return {
        "prompt_tokens": totals,
        "prompt_token_share": {view: value / grand for view, value in totals.items()},
        "note": "prompts only; re-measure including self-distilled targets before collecting C",
    }


def main() -> None:
    """Write one prompt file per view plus a manifest."""

    args = parse_args()
    sources = [name.strip() for name in args.sources.split(",") if name.strip()]
    unknown = [name for name in sources if name not in NATIVE_WEIGHTS]
    if unknown:
        raise SystemExit(f"Unknown sources {unknown}; expected from {sorted(NATIVE_WEIGHTS)}")

    dataset = load_metamath(args)
    missing = [name for name in REQUIRED_COLUMNS if name not in dataset.column_names]
    if missing:
        raise SystemExit(
            f"MetaMathQA columns {missing} not found; got {dataset.column_names}. "
            "Check that --metamath_path points at the MetaMathQA release."
        )
    print(f"loaded {len(dataset)} rows, columns={dataset.column_names}")
    index = index_questions(dataset, sources)
    rng = random.Random(args.seed)
    views, manifest = build_records(dataset, index, args, rng)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Any] = {}
    for view, records in views.items():
        if not records:
            continue
        path = out_dir / f"{args.prefix}_{view}.jsonl"
        with path.open("w", encoding="utf-8") as file:
            for record in records:
                file.write(json.dumps(record, ensure_ascii=False) + "\n")
        written[view] = {"path": str(path), "num_records": len(records)}

    manifest.update(
        {
            "seed": args.seed,
            "sources": sources,
            "mode": "all_views" if args.all_views else "quota",
            "aug_weights_override": args.aug_weights or None,
            "max_questions_per_source": args.max_questions_per_source,
            "files": written,
            "total_records": sum(v["num_records"] for v in written.values()),
        }
    )
    if args.tokenizer_path:
        manifest["tokens"] = token_shares(views, args.tokenizer_path)

    (out_dir / f"{args.prefix}_manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
